# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

version: 2

before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  -
    binary: jwt
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386
    main: ./main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/frankywahl/jwt-cli/cmd.GitRevision={{.FullCommit}} -X github.com/frankywahl/jwt-cli/cmd.Version={{.Version}} -X github.com/frankywahl/jwt-cli/cmd.CreatedAt={{.Date}}
archives:
-
  name_template: >-
    {{ .ProjectName }}_
    {{- .Version }}_
    {{- if eq .Os "darwin" }}macOS-
    {{- else if eq .Os "linux" }}Linux-
    {{- else if eq .Os "windows" }}Windows-
    {{- else }}{{ title .Os }}{{ end }}
    {{- if eq .Arch "amd64" }}64bit
    {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
-
  name: jwt
  directory: Formula
  homepage: "http://github.com/frankywahl/jwt-cli"
  description: "CLI interaction with JWT (JSON Web Tokens)"
  repository:
    owner: frankywahl
    name: homebrew-tap

dockers:
  -
    goos: linux
    goarch: amd64
    ids:
    - jwt
    image_templates:
    - "frankywahl/jwt:latest"
    - "frankywahl/jwt:{{ .Tag }}"
    - "frankywahl/jwt:v{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/frankywahl/jwt-cli:latest"
    - "ghcr.io/frankywahl/jwt-cli:{{ .Tag }}"
    dockerfile: .goreleaser.Dockerfile
    build_flag_templates:
    - "--pull"
    - "--build-arg=BUILD_VERSION={{.Version}}"
    - "--build-arg=BUILD_DATE={{.Date}}"
    - "--build-arg=REVISION={{.FullCommit}}"
    - "--build-arg=SOURCE={{.Env.SOURCE}}"
