on:
  push:
    branches:
      - main
  pull_request:

name: Run tests

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] # window-latest does not work yet
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: |
          go mod download
          go mod tidy -v

      - name: Vet
        if: matrix.platform == 'ubuntu-latest'
        run: make vet

      - name: fmt
        if: matrix.platform == 'ubuntu-latest'
        run: make fmt

      - name: Test
        run: make test
