on:
  release:
    types:
      - published

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: |
          go mod download
          go mod tidy -v

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Login Github Container Registry
        run: echo "${{ secrets.GORELEASER_GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set SOURCE Environment
        run: |
          echo 'SOURCE<<EOF' >> $GITHUB_ENV
          echo ${GITHUB_SERVER_URL}/${{ github.repository }} >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --rm-dist
